name: swamp
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  swamp_api:
    path: ../api
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 2e0ab5b548cb8e2d64ca24e0d7b4a6cfcc6d57fe
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_crypto
      ref: 1cc2988f680758fcb45c88b3905b0312d8c5a513
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_socket
      ref: 1cc2988f680758fcb45c88b3905b0312d8c5a513
  consoler:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/consoler
      ref: ca62a7ca874e32f12861f45848bf392e172429d2

dev_dependencies:
  build_runner: ^2.4.15
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
