name: swamp_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  cryptography: ^2.7.0
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: e19c3a25196ddbe2517e99bffce951164415a4d3
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_crypto
      ref: 83a13bc619b32398a16b44f406c06491b77f4f15
  web_socket_channel: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
