name: swamp_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 08928a4dc5ef638809b18c84f4f9bd64108fe18d
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_crypto
      ref: 459deccbfacedc115f28ae0095c5b531c70d7cc7
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  test: ^1.24.0
