name: swamp_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  networker: any
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_crypto
      ref: 42454669f8c95b4ca24fb52411aaf41c5a90761c
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependency_overrides:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: d220c490bb05e9bae565980cfd65527582adb9a0
