name: swamp_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 213c6382f196ee93c4c43ca911cdb26a38317e39
  networker_crypto:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker_crypto
      ref: e901983295b103f2fe27738e8f2cbf35941d99ea
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  test: ^1.24.0
