name: Dart build

on:
  push:
    branches:
      - "*"
    tags:
      - stable
      - nightly
  release:
    types: [published]
  pull_request:
jobs:
  build-server:
    defaults:
      run:
        working-directory: server
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-24.04
            label: linux-x86_64
          - name: ubuntu-24.04-arm
            label: linux-arm64
          - name: windows-2025
            label: windows-x86_64
          - name: macos-latest
            label: macos
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v5
      - name: Install yq
        if: ${{ matrix.os.name == 'windows-2025' }}
        run: choco install yq
      - name: Extract Dart SDK version from pubspec.yaml
        id: dart_version
        shell: bash
        run: |
          sdk_version=$(yq e '.environment.sdk' pubspec.yaml)
          sdk_version="${sdk_version#^}"  # Removes leading '^' if present
          echo "DART_SDK_VERSION=$sdk_version" >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}
      - name: Print Dart SDK version
        run: |
          dart --version
      - name: Install dependencies
        run: |
          dart pub get
      - name: Compile
        run: |
          dart compile exe bin/swamp.dart
      - name: Create directory
        run: |
          mkdir -p server-build
          mv bin/swamp.exe server-build/
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: server-build-${{ matrix.os.label }}
          path: server/server-build
  build-docker:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v5
      - name: Set Docker tag
        id: docker_tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "tag=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/v* || "${GITHUB_REF}" == "refs/tags/stable" || "${GITHUB_REF}" == "refs/tags/nightly" ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "tag=unknown" >> $GITHUB_ENV
          fi
      - name: Log Docker tag
        run: echo "Docker tag is ${{ env.tag }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: ${{ env.tag != 'unknown' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: linwooddev/swamp:${{ env.tag }}
  deploy:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    outputs:
      version: ${{ steps.setup.outputs.SWAMP_VERSION }}
    needs:
      - build-server
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v5
        env:
          CI_PAT: ${{ secrets.CI_PAT }}
        with:
          token: ${{ env.CI_PAT }}
      - name: Setup git
        id: setup
        run: |
          SWAMP_VERSION=$(yq e '.version' server/pubspec.yaml)
          echo "SWAMP_VERSION=${SWAMP_VERSION}" >> $GITHUB_ENV
          echo "SWAMP_VERSION=${SWAMP_VERSION}" >> $GITHUB_OUTPUT
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - uses: actions/download-artifact@v5
        with:
          name: server-build-linux-x86_64
          path: server-build-linux-x86_64/
      - uses: actions/download-artifact@v5
        with:
          name: server-build-linux-arm64
          path: server-build-linux-arm64/
      - uses: actions/download-artifact@v5
        with:
          name: server-build-windows-x86_64
          path: server-build-windows-x86_64/
      - uses: actions/download-artifact@v5
        with:
          name: server-build-macos
          path: server-build-macos/
      - name: 📦 Zip artifacts
        run: |
          zip -r linwood-swamp-server-windows-x86_64.zip server-build-windows-x86_64/*
          tar -C server-build-linux-x86_64 -czf linwood-swamp-server-linux-x86_64.tar.gz .
          tar -C server-build-linux-arm64 -czf linwood-swamp-server-linux-arm64.tar.gz .
          zip -r linwood-swamp-server-macos.zip server-build-macos/*
      - name: Configure git
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
        run: |
          git --version
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions"
          git pull --tags
      - name: Add checksums
        run: |
          output_file="checksums.txt"

          # Empty the output file if it exists
          > "$output_file"

          # Find and loop through all files starting with "linwood-swamp" in the current directory
          for file in linwood-swamp*; do
            # Check if the file exists (in case no matches were found)
            if [ -f "$file" ]; then
              # Append sha256sum to the output file in the format "hash  filename"
              sha256sum "$file" >> "$output_file"
            fi
          done

          echo "SHA256 hashes for files starting with 'linwood-swamp' saved to $output_file"
      - name: 🚀 Deploy stable
        if: ${{ github.ref == 'refs/tags/stable' || (github.event_name == 'release' && !github.event.release.prerelease) }}
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          prerelease: true
          tag_name: stable
          files: |
            linwood-swamp-server-linux-x86_64.tar.gz
            linwood-swamp-server-linux-arm64.tar.gz
            linwood-swamp-server-windows-x86_64.zip
            linwood-swamp-server-macos.zip
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Deploy nightly
        if: ${{ github.ref == 'refs/tags/nightly' }}
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          prerelease: true
          tag_name: nightly
          files: |
            linwood-swamp-server-linux-x86_64.tar.gz
            linwood-swamp-server-linux-arm64.tar.gz
            linwood-swamp-server-windows-x86_64.zip
            linwood-swamp-server-macos.zip
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            linwood-swamp-server-linux-x86_64.tar.gz
            linwood-swamp-server-linux-arm64.tar.gz
            linwood-swamp-server-windows-x86_64.zip
            linwood-swamp-server-macos.zip
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
