name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        projects: [api, server, tools]
    defaults:
      run:
        working-directory: ${{ matrix.projects }}
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v4
      - name: Print Dart SDK version
        run: |
          dart --version
      - name: Install dependencies
        run: |
          dart pub get
      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib
      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: |
          dart analyze --fatal-infos
      - name: Run build_runner
        if: matrix.projects != 'tools'
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Test for git changes
        run: git diff --exit-code
